name: Publish package

on:
  release:
    types: [published] # run when a new release is published
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo name # This can be deleted when manually setting the package name
        run: |
          "echo name=$(echo ${{ github.repository }} | sed s:*/::) >> GITHUB_ENV"
      - name: Upload Thunderstore Package
        uses: GreenTF/upload-thunderstore-package@v1
        with:
          community: northstar
          # Name of the team to publish the mod under
          # This should be modified if your github username is different than your team name on Thunderstore
          namespace: ${{ github.repository_owner }}
          # Name of the package
          name: ${{ env.name }} # This can be modified if the package name differs from the repo name
          # Package version to publish
          version: ${{ github.ref_name }} # This is the tag that was created in the release
          # Description of the mod
          description: Example mod description # <----- UPDATE THIS
          # Thunderstore API token
          token: ${{ secrets.TS_KEY }} 
          # Directory to wrap the contents of the repo in
          wrap: mods # This will wrap your Author.ModName folder in a mods/ folder before publishing
